### ISSUE TITLE
Database is the cause of Corona virus

### ISSUE THREAD

**Issue by leecottrellPTC** [JJFoley27/IllinoisMVC#1]
You are patient 0
Just kidding, using your project in lecture

:)

**Comment by JJFoley27** [comment]
Corona virus has been cured, Database purged of infection @leecottrellPTC 
Next to remove Lyme disease since you can't have corona without lime

**Comment by devinw5500** [comment]
Not sure how it got there in the first place, none of us are 21 to my knowledge. I'll be giving the database breathalyzer tests daily to avoid this again.
